// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * Todo
 */
export type Todo = {
    /**
     * Title
     */
    title: string;
    /**
     * Completed
     */
    completed?: boolean;
    /**
     * Id
     */
    id?: number | null;
};

/**
 * TodoCreate
 */
export type TodoCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Completed
     */
    completed?: boolean;
};

/**
 * TodoUpdate
 */
export type TodoUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Completed
     */
    completed?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListTodosData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/todos';
};

export type ListTodosErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTodosError = ListTodosErrors[keyof ListTodosErrors];

export type ListTodosResponses = {
    /**
     * Response Listtodos
     *
     * Successful Response
     */
    200: Array<Todo>;
};

export type ListTodosResponse = ListTodosResponses[keyof ListTodosResponses];

export type CreateTodoData = {
    body: TodoCreate;
    path?: never;
    query?: never;
    url: '/todos';
};

export type CreateTodoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTodoError = CreateTodoErrors[keyof CreateTodoErrors];

export type CreateTodoResponses = {
    /**
     * Successful Response
     */
    201: Todo;
};

export type CreateTodoResponse = CreateTodoResponses[keyof CreateTodoResponses];

export type DeleteTodoData = {
    body?: never;
    path: {
        /**
         * Todo Id
         */
        todo_id: number;
    };
    query?: never;
    url: '/todos/{todo_id}';
};

export type DeleteTodoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTodoError = DeleteTodoErrors[keyof DeleteTodoErrors];

export type DeleteTodoResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteTodoResponse = DeleteTodoResponses[keyof DeleteTodoResponses];

export type GetTodoData = {
    body?: never;
    path: {
        /**
         * Todo Id
         */
        todo_id: number;
    };
    query?: never;
    url: '/todos/{todo_id}';
};

export type GetTodoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTodoError = GetTodoErrors[keyof GetTodoErrors];

export type GetTodoResponses = {
    /**
     * Successful Response
     */
    200: Todo;
};

export type GetTodoResponse = GetTodoResponses[keyof GetTodoResponses];

export type UpdateTodoData = {
    body: TodoUpdate;
    path: {
        /**
         * Todo Id
         */
        todo_id: number;
    };
    query?: never;
    url: '/todos/{todo_id}';
};

export type UpdateTodoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTodoError = UpdateTodoErrors[keyof UpdateTodoErrors];

export type UpdateTodoResponses = {
    /**
     * Successful Response
     */
    200: Todo;
};

export type UpdateTodoResponse = UpdateTodoResponses[keyof UpdateTodoResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
