// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createTodo, deleteTodo, getTodo, healthCheck, listTodos, type Options, updateTodo } from '../sdk.gen';
import type { CreateTodoData, CreateTodoError, CreateTodoResponse, DeleteTodoData, DeleteTodoError, DeleteTodoResponse, GetTodoData, GetTodoError, GetTodoResponse, HealthCheckData, HealthCheckResponse, ListTodosData, ListTodosError, ListTodosResponse, UpdateTodoData, UpdateTodoError, UpdateTodoResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listTodosQueryKey = (options?: Options<ListTodosData>) => createQueryKey('listTodos', options);

/**
 * List Todos
 *
 * Get all todos.
 */
export const listTodosOptions = (options?: Options<ListTodosData>) => queryOptions<ListTodosResponse, ListTodosError, ListTodosResponse, ReturnType<typeof listTodosQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTodos({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTodosQueryKey(options)
});

/**
 * Create Todo
 *
 * Create a new todo.
 */
export const createTodoMutation = (options?: Partial<Options<CreateTodoData>>): UseMutationOptions<CreateTodoResponse, CreateTodoError, Options<CreateTodoData>> => {
    const mutationOptions: UseMutationOptions<CreateTodoResponse, CreateTodoError, Options<CreateTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Todo
 *
 * Delete a todo.
 */
export const deleteTodoMutation = (options?: Partial<Options<DeleteTodoData>>): UseMutationOptions<DeleteTodoResponse, DeleteTodoError, Options<DeleteTodoData>> => {
    const mutationOptions: UseMutationOptions<DeleteTodoResponse, DeleteTodoError, Options<DeleteTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTodoQueryKey = (options: Options<GetTodoData>) => createQueryKey('getTodo', options);

/**
 * Get Todo
 *
 * Get a specific todo by ID.
 */
export const getTodoOptions = (options: Options<GetTodoData>) => queryOptions<GetTodoResponse, GetTodoError, GetTodoResponse, ReturnType<typeof getTodoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTodo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTodoQueryKey(options)
});

/**
 * Update Todo
 *
 * Update an existing todo.
 */
export const updateTodoMutation = (options?: Partial<Options<UpdateTodoData>>): UseMutationOptions<UpdateTodoResponse, UpdateTodoError, Options<UpdateTodoData>> => {
    const mutationOptions: UseMutationOptions<UpdateTodoResponse, UpdateTodoError, Options<UpdateTodoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateTodo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthCheckQueryKey = (options?: Options<HealthCheckData>) => createQueryKey('healthCheck', options);

/**
 * Health Check
 *
 * Health check endpoint.
 */
export const healthCheckOptions = (options?: Options<HealthCheckData>) => queryOptions<HealthCheckResponse, DefaultError, HealthCheckResponse, ReturnType<typeof healthCheckQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthCheck({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckQueryKey(options)
});
